### PR TITLE
try/except clause on imports + __version__ in lib

### PR DESCRIPTION
**Pull request by RogueM**

### CODE REVIEW

**Comment by RogueM** [comment]
this one probably needs a bit of scrutiny before packaging and pushing, just to be sure, since the changes are more than cosmetic.

**Comment by RogueM** [comment]
right, I see that those were some recent changes for Automation pHAT support. Makes sense, but best to stick to import at front of file, just one of those things that ease up QA.

**Comment by RogueM** [comment]
I have restored pHAT support, but moved imports at front of file for clarity, with try/except clause to booth... hopefully I haven't screwed up anything?

**Comment by Gadgetoid** [comment]
Looks like it works, with the exception of the AttributeError which needed to be a NameError to catch the non-existence of sn3218 rather than the lack of attribute i2c: https://github.com/pimoroni/automation-hat/commit/f13f2b1f7122d8e7d389e06c79f215a4c670fff2

**Comment by RogueM** [comment]
oh? Got an AttributeError when I tried, that's strange.

**Comment by RogueM** [comment]
aaah, yes, that was when I had sn3218=None outside the catch!

**Pull request merged**
